### ISSUE TITLE
Naming Collision with RPC argument object and parameters if you use the name "request"

### ISSUE THREAD

**Issue by dries007** [danielgtaylor/python-betterproto#369] opened 2022-04-18 13:19 UTC
If you generate the following file, there is a naming collision in the Stub class:

```protobuf
syntax = "proto3";
import "google/protobuf/empty.proto";

message QueryRequest {
  map<string, string> request = 1;
}

service Query {
  rpc query(QueryRequest) returns (google.protobuf.Empty);
}
```

```python
class QueryStub(betterproto.ServiceStub):
    async def query(
        self, *, request: Dict[str, str] = None
    ) -> "betterproto_lib_google_protobuf.Empty":

        request = QueryRequest()   # <<< 
        request.request = request

        return await self._unary_unary(
            "/opso_proto.query.Query/query",
            request,
            betterproto_lib_google_protobuf.Empty,
        )
```

I guess that this naming is internal only, so it ought to be possible to use something else if the name 'request' is used in the parameters.

Kind regards,
Dries

**Comment by Gobot1234** [comment] 2022-04-18 13:37
Duplicate of #257

**Closed by Gobot1234** 2022-04-18 13:37 UTC
