### ISSUE TITLE
Parsing from bytes to python poor performance

### ISSUE THREAD

**Issue by nirdunetz** [danielgtaylor/python-betterproto#296] opened 2021-12-02 11:06 UTC
I have a protobuf message and I generated python data classed using betterproto
When converting from bytes to python object:
`res = MyPthonBetterProto().parse(bytes)`
I encounter poor performance when the message(bytes) size is very big - around 800 ms
*when parsing small messages its take less than 10 ms
Any idea how to improve it?

**Comment by Gobot1234** [comment] 2021-12-02 12:36
This is an active topic of inquiry for me although my last attempt at this wasn't very successful using mypyc but with the improvements to the compiler maybe it's slightly more performant now.

**Comment by Gobot1234** [comment] 2021-12-02 20:59
This is a duplicate of #153

**Closed by Gobot1234** 2021-12-02 20:59 UTC
Labels: duplicate
