### ISSUE TITLE
Cannot compile proto files with v2.0.0 

### ISSUE THREAD

**Issue by lamehost** [danielgtaylor/python-betterproto#331] opened 2022-02-02 09:50 UTC
Dear developers,

I took a look at the documentation provided for v2.0.0, but i couldn't find anything that stated that you cannot longer compile .proto files with that version.

Anyway, it always fails with status code 1:
```
marco@lilith:~/test$ virtualenv venv
created virtual environment CPython3.9.10.final.0-64 in 150ms
  creator CPython3Posix(dest=/home/marco/test/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/marco/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


marco@lilith:~/test$ source venv/bin/activate


(venv) marco@lilith:~/test$ pip install git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b4
Collecting git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b4
  Cloning https://github.com/danielgtaylor/python-betterproto.git (to revision v2.0.0b4) to /tmp/pip-req-build-dskhzrfb
  Running command git clone --filter=blob:none -q https://github.com/danielgtaylor/python-betterproto.git /tmp/pip-req-build-dskhzrfb
  Running command git checkout -q 6dd7baa26cd9930b0013d0f6f0b7eaf84541deed
  Resolved https://github.com/danielgtaylor/python-betterproto.git to commit 6dd7baa26cd9930b0013d0f6f0b7eaf84541deed
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting grpclib<0.5.0,>=0.4.1
  Using cached grpclib-0.4.2-py3-none-any.whl
Collecting python-dateutil<3.0,>=2.8
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting h2<5,>=3.1.0
  Using cached h2-4.1.0-py3-none-any.whl (57 kB)
Collecting multidict
  Using cached multidict-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting hyperframe<7,>=6.0
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting hpack<5,>=4.0
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Building wheels for collected packages: betterproto
  Building wheel for betterproto (pyproject.toml) ... done
  Created wheel for betterproto: filename=betterproto-2.0.0b4-py3-none-any.whl size=60908 sha256=6b807038df17a7896cc1f98b42f64eed24c2f350b6d10b2854501f8b9b7d3d1e
  Stored in directory: /tmp/pip-ephem-wheel-cache-m5jycn27/wheels/dd/fd/d1/0678d840080bb8a76c718b576a5f15bd31b6ef3b2fa459e2bf
Successfully built betterproto
Installing collected packages: hyperframe, hpack, six, multidict, h2, python-dateutil, grpclib, betterproto
Successfully installed betterproto-2.0.0b4 grpclib-0.4.2 h2-4.1.0 hpack-4.0.0 hyperframe-6.0.1 multidict-6.0.2 python-dateutil-2.8.2 six-1.16.0


(venv) marco@lilith:~/test$ pip install grpcio-tools
Collecting grpcio-tools
  Using cached grpcio_tools-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Collecting protobuf<4.0dev,>=3.5.0.post1
  Using cached protobuf-3.19.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting grpcio>=1.43.0
  Using cached grpcio-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from grpcio-tools) (59.6.0)
Requirement already satisfied: six>=1.5.2 in ./venv/lib/python3.9/site-packages (from grpcio>=1.43.0->grpcio-tools) (1.16.0)
Installing collected packages: protobuf, grpcio, grpcio-tools
Successfully installed grpcio-1.43.0 grpcio-tools-1.43.0 protobuf-3.19.4


(venv) marco@lilith:~/test$ cat example.proto 
syntax = "proto3";

package hello;

// Greeting represents a message you can tell a user.
message Greeting {
  string message = 1;
}


(venv) marco@lilith:~/test$ mkdir lib


(venv) marco@lilith:~/test$ python -m grpc_tools.protoc -I . --python_betterproto_out=lib example.proto
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.


(venv) marco@lilith:~/test$ pip install git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b3
Collecting git+https://github.com/danielgtaylor/python-betterproto.git@v2.0.0b3
  Cloning https://github.com/danielgtaylor/python-betterproto.git (to revision v2.0.0b3) to /tmp/pip-req-build-7bq_6du5
  Running command git clone --filter=blob:none -q https://github.com/danielgtaylor/python-betterproto.git /tmp/pip-req-build-7bq_6du5
  Running command git checkout -q 02e41afd09f0050a10fea764b15279b82cdd6e6b
  Resolved https://github.com/danielgtaylor/python-betterproto.git to commit 02e41afd09f0050a10fea764b15279b82cdd6e6b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: python-dateutil<3.0,>=2.8 in ./venv/lib/python3.9/site-packages (from betterproto==2.0.0b3) (2.8.2)
Requirement already satisfied: grpclib<0.5.0,>=0.4.1 in ./venv/lib/python3.9/site-packages (from betterproto==2.0.0b3) (0.4.2)
Requirement already satisfied: h2<5,>=3.1.0 in ./venv/lib/python3.9/site-packages (from grpclib<0.5.0,>=0.4.1->betterproto==2.0.0b3) (4.1.0)
Requirement already satisfied: multidict in ./venv/lib/python3.9/site-packages (from grpclib<0.5.0,>=0.4.1->betterproto==2.0.0b3) (6.0.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil<3.0,>=2.8->betterproto==2.0.0b3) (1.16.0)
Requirement already satisfied: hpack<5,>=4.0 in ./venv/lib/python3.9/site-packages (from h2<5,>=3.1.0->grpclib<0.5.0,>=0.4.1->betterproto==2.0.0b3) (4.0.0)
Requirement already satisfied: hyperframe<7,>=6.0 in ./venv/lib/python3.9/site-packages (from h2<5,>=3.1.0->grpclib<0.5.0,>=0.4.1->betterproto==2.0.0b3) (6.0.1)
Building wheels for collected packages: betterproto
  Building wheel for betterproto (pyproject.toml) ... done
  Created wheel for betterproto: filename=betterproto-2.0.0b3-py3-none-any.whl size=59711 sha256=6336413255d8c7b4769a4823444fe55e9635286809e8415d7841dcf1fb65ccba
  Stored in directory: /tmp/pip-ephem-wheel-cache-ufp9duj1/wheels/ee/2c/5b/f35834e2b7abec1c05912d2311fdf5420293caf4a0ffd72fb5
Successfully built betterproto
Installing collected packages: betterproto
  Attempting uninstall: betterproto
    Found existing installation: betterproto 2.0.0b4
    Uninstalling betterproto-2.0.0b4:
      Successfully uninstalled betterproto-2.0.0b4
Successfully installed betterproto-2.0.0b3


(venv) marco@lilith:~/test$ python -m grpc_tools.protoc -I . --python_betterproto_out=lib example.proto
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

Is it because the branch is still under development?

**Comment by Gobot1234** [comment] 2022-02-02 13:03
Have you tried installing from master? That might fix the error.

**Comment by lamehost** [comment] 2022-02-02 13:09
I have tried to install from master and the very same thing happens:

```
marco@lilith:~/test$ virtualenv venv
created virtual environment CPython3.9.10.final.0-64 in 217ms
  creator CPython3Posix(dest=/home/marco/test/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/marco/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
marco@lilith:~/test$ source venv/bin/activate


(venv) marco@lilith:~/test$ pip install git+https://github.com/danielgtaylor/python-betterproto.git
Collecting git+https://github.com/danielgtaylor/python-betterproto.git
  Cloning https://github.com/danielgtaylor/python-betterproto.git to /tmp/pip-req-build-ov3n8cwl
  Running command git clone --filter=blob:none -q https://github.com/danielgtaylor/python-betterproto.git /tmp/pip-req-build-ov3n8cwl
  Resolved https://github.com/danielgtaylor/python-betterproto.git to commit eeddc844a5bc17c569f1e50f4e812878ac974c34
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting grpclib<0.5.0,>=0.4.1
  Using cached grpclib-0.4.2-py3-none-any.whl
Collecting python-dateutil<3.0,>=2.8
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting h2<5,>=3.1.0
  Using cached h2-4.1.0-py3-none-any.whl (57 kB)
Collecting multidict
  Using cached multidict-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting hyperframe<7,>=6.0
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting hpack<5,>=4.0
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Building wheels for collected packages: betterproto
  Building wheel for betterproto (pyproject.toml) ... done
  Created wheel for betterproto: filename=betterproto-2.0.0b4-py3-none-any.whl size=60294 sha256=f642686256be388f583c5ff7e89fbe8df4e6b06d52a753555cffd675720be481
  Stored in directory: /tmp/pip-ephem-wheel-cache-bmpjyufk/wheels/94/47/23/1c837368baafe9af963976c6fc694dd7d38c4504d445917639
Successfully built betterproto
Installing collected packages: hyperframe, hpack, six, multidict, h2, python-dateutil, grpclib, betterproto
Successfully installed betterproto-2.0.0b4 grpclib-0.4.2 h2-4.1.0 hpack-4.0.0 hyperframe-6.0.1 multidict-6.0.2 python-dateutil-2.8.2 six-1.16.0


(venv) marco@lilith:~/test$ pip install grpcio-tools
Collecting grpcio-tools
  Using cached grpcio_tools-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Collecting protobuf<4.0dev,>=3.5.0.post1
  Using cached protobuf-3.19.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from grpcio-tools) (59.6.0)
Collecting grpcio>=1.43.0
  Using cached grpcio-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
Requirement already satisfied: six>=1.5.2 in ./venv/lib/python3.9/site-packages (from grpcio>=1.43.0->grpcio-tools) (1.16.0)
Installing collected packages: protobuf, grpcio, grpcio-tools
Successfully installed grpcio-1.43.0 grpcio-tools-1.43.0 protobuf-3.19.4


(venv) marco@lilith:~/test$ cat example.proto 
syntax = "proto3";

package hello;

// Greeting represents a message you can tell a user.
message Greeting {
  string message = 1;
}


(venv) marco@lilith:~/test$ python -m grpc_tools.protoc -I . --python_betterproto_out=lib example.proto
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

While everything works if i don't try to build with betterproto:
```
(venv) marco@lilith:~/test$ python -m grpc_tools.protoc -I . --python_out=. example.proto


(venv) marco@lilith:~/test$ cat example
example_pb2.py  example.proto   
(venv) marco@lilith:~/test$ cat example_pb2.py 
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='hello',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x05hello\"\x1b\n\x08Greeting\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3'
)




_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='hello.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.Greeting.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:hello.Greeting)
  })
_sym_db.RegisterMessage(Greeting)


# @@protoc_insertion_point(module_scope)
(venv) marco@lilith:~/test$ 
```

**Comment by Gobot1234** [comment] 2022-02-02 13:28
I'm sorry I can't reproduce this on master or on 2.0.0b4 and considering we have CI setup I'm not entirely sure what can be done about this on our end. Have you checked that things are being installed to the right places?

**Comment by lamehost** [comment] 2022-02-02 14:48
I have created Dockerfile from which i can reproduce:
```
# *** Base ***
FROM python:3.9.1-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

# Install deps
RUN pip install --no-cache-dir \
    git+https://github.com/danielgtaylor/python-betterproto.git \
    grpcio-tools

RUN echo 'syntax = "proto3";' >> /example.proto && \
    echo '' >> /example.proto && \
    echo 'package hello;' >> /example.proto && \
    echo '' >> /example.proto && \
    echo '// Greeting represents a message you can tell a user.' >> /example.proto && \
    echo 'message Greeting {' >> /example.proto && \
    echo '  string message = 1;' >> /example.proto && \
    echo '}' >> /example.proto

# Start
CMD [ "python3", "-m", "grpc_tools.protoc", "-I", ".", "--python_betterproto_out=lib", "example.proto" ]
```

Just build and run it:
```
docker build -t issue-331 . >> /dev/null
docker run -it --rm issue-331
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

You can also check that everything works without betterproto:
```
docker run -it --rm issue-331 /bin/bash
python -m grpc_tools.protoc -I . --python_out=. example.proto
cat example_pb2.py
```

Could you please give it a try?

**Comment by Gobot1234** [comment] 2022-02-02 14:52
I've just realised this is a duplicate of #269, you need to install betterproto[compiler]

**Closed by Gobot1234** 2022-02-02 14:52 UTC
