### ISSUE TITLE
The service methods should be passed the message objects, **not** their fields.

### ISSUE THREAD

**Issue by FHTMitchell** [danielgtaylor/python-betterproto#287] opened 2021-11-19 16:42 UTC
I absolutely love betterproto but some of my protobuf files are very complicated with many fields and nested structures and I need to pass a lot of data around to a lot of different places. The objects I use to pass those around are, naturally, the dataclasses betterproto provides. However, betterproto splits these objects up so I end up with code that looks like 

```python
class VolService(VolServiceBase):
    async def run_vol_pipeline(
        self,
        oc_key: "OcKey",  # nested
        source: str,
        source_topic: str,
        cycle_id: str,
        cycle_time: datetime,
        chain_size: int,
        cycle_size: int,
        priced_count: int,
        unavailable_count: int,
        bad_count: int,
        snapshots: Optional[List["OptionSnapshot"]],  # repeated nested
    ) -> AsyncIterator["PyvolResult"]:
        
        req = PyvolRequest(
        oc_key,
        source,
        source_topic,
        cycle_id,
        cycle_time,
        chain_size,
        cycle_size,
        priced_count,
        unavailable_count,
        bad_count,
        snapshots,
        )
 ```
 
whereas if you pass the object the method signature is cleaner and users can easily extract fields anywhere down the call stack.

```python
class VolService(VolServiceBase):
    async def run_vol_pipeline(self, request: PyvolRequest) -> AsyncIterator["PyvolResult"]:
        ...
```

This is actually how grpclib works! I also feel the same way about the clients. Why not allow us to pass a message object directly instead of having to do something like

```python
async def query(req: fx.FxRequest) -> fx.FxResponse:
    service = fx.FxServiceStub(channel)  # the service stub
    asdict = {f.name: getattr(req, f.name) for f in dataclasses.fields(req)}
    return await service.run_fx_pipeline(**asdict)
```

It gives the user more control about how they want to handle data. It's fully typed so we don't lose anything.

**Comment by Gobot1234** [comment] 2021-11-30 22:40
This sounds like a good idea to me, interested as to @danielgtaylor's POV on this.

**Comment by efokschaner** [comment] 2022-01-05 00:40
I also would like this. I found myself having to reconstruct proto messages from the params because I have other functions which are expecting to operate on the defined message.

**Comment by Gobot1234** [comment] 2022-01-18 21:25
Fixed in https://github.com/danielgtaylor/python-betterproto/commit/d260f071e01657287888e15b73623305b56b4d9f

**Closed by Gobot1234** 2022-01-18 21:25 UTC
Labels: enhancement

**Comment by augi** [comment] 2022-09-29 12:19
Hello, I know I'm late to the party but I would like to express my concerns 🙏 

For us, the _flattening_ of the request message is one of the best features of betterproto, so we would like to keep it even for 2.x releases 🙏 

Please note that Style Guide by Google and Uber recommend having dedicated messages for both requests and responses, for each method individually.
* https://developers.google.com/protocol-buffers/docs/style#services
* https://github.com/uber/prototool/tree/dev/style#servicesrpcs

Also, the [DEFAULT category of buf lint](https://docs.buf.build/lint/rules#default) command includes `RPC_REQUEST_RESPONSE_UNIQUE`, `RPC_REQUEST_STANDARD_NAME`, and `RPC_RESPONSE_STANDARD_NAME`.

If I understand it correctly, the main use-case for this change is that when someone reuses the request message in another message, then they have to construct it again. This pattern doesn't go directly against these rules but IMHO it is worth creating a new _inner_ message instead (and not reusing `MyMethod2Request` in another message) 🙏 

I strongly believe that the ease of having the method signatures without the wrapping message is more valuable than support of this edge use-case 🙏

**Comment by augi** [comment] 2022-09-29 15:44
> > If I understand it correctly, the main use-case for this change is that when someone reuses the request message in another message, then they have to construct it again
> 
> That's _not_ the use case. The use case is that these objects can be excessively large and will often be passed very far down the call tree before being destructed (or queries constructed) in large programs. It is cleaner to pass around the message objects but if the functions take kwargs then you need to manually construct/destruct these objects at the query site _for no reason_. This is what I describe in the OP.

It is actually the same I'm describing so it looks like I understand the use-case correctly 🙏 What I wanted to say is that according to the Style Guides, the request message should be named according to the method name, and thus it is not well suitable for reuse. Instead, a new message with a large number of parameters should be used, and this should be included in the non-reusable `MyMethodRequest` message.

So the style guides intend to drive you to this design:
```proto
message MyMethodRequest {
  MyDomainValues values = 1;
}

message MyDomainValues {
  // the large number of domain specific parameters here
}
```

So if you follow this style guide, you are fine with the flattening.

> I'd like to know _why_ you think the flattening is useful? It's less flexible and considered a code smell to have a large numbers of keyword arguments.

That's true for general programming languages 👌 But this is IMHO different because the request message here is just a transport layer structure. This is actually caused by gRPC/Protobuf design where a method must have exactly one input and output parameter.
The flattening is IMHO useful because it decreases the complexity by removal of the transport layer request message.

> If you want prior art, not a single other library I could find destructs (or constructs) the objects as part of the message API, whether python or others.
> 
> * [go (google)](https://grpc.io/docs/languages/go/quickstart/#update-the-server)
> * [python (goolge)](https://grpc.io/docs/languages/python/quickstart/#update-the-server)
> * [rust (tonic)](https://github.com/hyperium/tonic/blob/master/examples/src/grpc-web/server.rs#L17)
> * [python (grpclib)](https://grpclib.readthedocs.io/en/latest/client.html#grpclib.client.Stream.send_message)

Yep, I have also experience with C#, Java, and Scala libraries. And this is what I like on betterproto because it simplifies the usage.

**Comment by jbkoh** [comment] 2022-10-28 21:59
hi @FHTMitchell  thanks for putting all the detailed cases. It's helpful to understand the context better.

I'm heavily using betterproto for server side implementation and my main argument is it's reducing the abstraction of grpc as an RPC, which is at best considered to be just a function (I wish stream methods follow the same, though I don't know how feasible it is in the current betterproto implementation). Having a request message as an input is exposing the transport layer as augi argued, which the coder doesn't necessarily need to understand or spend time on. augi's argument for the packing arguments into an object (DomainObject) is I believe when you want to pass it around as a whole for some reason, which I think is the root cause of our different opinions.

I'd like to understand your reasoning on why "LiveClient" is necessary in your example. I'm generally discouraged to use generic types as in Python everything is an object anyway, and you can be more type-safe at the code level if you natively use stubs. Without wrapping all the requests as a `R`, the needs for packing request arguments into a single request object should be rare. I might be missing something and would love to learn from your experiences.

So, really, your 1 and 3 depend on 2 because your argument is that basically handling the set of arguments in the request as a whole is a common case. I'd like to learn more.

Thanks!

**Comment by FHTMitchell** [comment] 2022-10-31 10:41
> Having a request message as an input is exposing the transport layer as augi argued, which the coder doesn't necessarily need to understand or spend time on. augi's argument for the packing arguments into an object (DomainObject) is I believe when you want to pass it around as a whole for some reason, which I think is the root cause of our different opinions.

I can agree this is the root cause of the different opinions, but I don't see how writing `service.endpoint(EndpointRequest(a=1, b=None))` is significantly more or less abstract than writing `service.endpoint(a=1, b=None)`. You're just packing the data into an object rather than splitting it up, what's the big deal? This is a pattern that is reasonable common in python and *extremely* common in other languages, especially in RPCs and especially on the server side. It even helps with things like logging, since the `repr` is already created for you, something even more important in gRPC where you can forget to set defaults. 

It also comes back to the assumption that I control the protobufs themselves, which is not necessarily true. I can't just change `MyRequest(a, b)` to `MyRequest(MyDomainObject(a, b))` on a whim. 

> I'd like to understand your reasoning on why "LiveClient" is necessary in your example. I'm generally discouraged to use generic types as in Python everything is an object anyway, and you can be more type-safe at the code level if you natively use stubs.

I don't understand this, how do stubs replace generics? Generics are incredibly powerful in programming, full-stop. Python is no exception. The reason I do it here is because I want to wrap all my requests in some context for logging/metrics/tracing/retries/etc, and having a single loader class that handles all that (when I have >10 different data sources) is useful for reducing code duplication. 

> So, really, your 1 and 3 depend on 2 because your argument is that basically handling the set of arguments in the request as a whole is a common case. I'd like to learn more.

Sorry if I gave that impression, that's not what I meant. 2 is separate from 1 and 3. 1 and 3 are for where I want to hold onto the request object, often because it's cached or because I'm following the "context" method of server design. That is, for complex servers, it is useful to pass around the whole request context (a la flask but without the globals). This is because it makes refactoring significantly less hard because all mid-level functions have access to the whole request context so if you need a bit of data you didn't previously you don't have to change layers of functions to pass it down to you. 

For requests its also useful because you want information in the request to be used for logging/tracing/metrics as I said above.
