### ISSUE TITLE
Encode oneOfs as Python unions for reliable handling.

### ISSUE THREAD

**Issue by heimalne** [danielgtaylor/python-betterproto#452] opened 2023-01-10 13:03 UTC
Currently, betterproto encodes protobuf oneOfs as a attributes of the enclosing class with one attribute per oneOf alternative. This leads to an akward runtime-encoding, where all attributes get an object with dummy data and the actual oneOf has non-dummy data. To distinguish those cases we need helper functions like `serialized_on_wire()` or `which_on_of()`, and the mypy type checker can't help us to ensure we've covered all alternatives. A better encoding would be Python unions (a.k.a Choice types), which get full exhaustiveness-support mypy support with Python 3.11 (https://docs.python.org/3.11/library/typing.html#typing.assert_never) and backwards compatible workaround for older Python versions (https://hakibenita.com/python-mypy-exhaustive-checking)

Would this other union encoding be suitable for betterproto?

**Comment by Gobot1234** [comment] 2023-01-10 13:29
Duplicate of #358

**Closed by Gobot1234** 2023-01-10 13:29 UTC
