### ISSUE TITLE
Support for pbtxt

### ISSUE THREAD

**Issue by joseparajelesGL** [danielgtaylor/python-betterproto#431] opened 2022-10-03 19:36 UTC
While writing a [text output](https://github.com/PrimerAI/tenant-operator/blob/eric/component_params_mapping/controllers/test_data/only_one/kustomization.yaml) from the compiled I get the following error due to the lack of a description.
```
Traceback (most recent call last):
  File "test2.py", line 8, in <module>
    string_format = text_format.MessageToString(config)
  File "/Users/jpp/.virtualenvs/.../lib/python3.8/site-packages/google/protobuf/text_format.py", line 187, in MessageToString
    printer.PrintMessage(message)
  File "/Users/jpp/.virtualenvs/.../lib/python3.8/site-packages/google/protobuf/text_format.py", line 428, in PrintMessage
    if (message.DESCRIPTOR.full_name == _ANY_FULL_TYPE_NAME and
AttributeError: 'ModelConfig' object has no attribute 'DESCRIPTOR'
```

The [proto file is from the Nvidia Triton Server ](https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto) using the following snippet

```python
from inference import ModelConfig
from google.protobuf import text_format

config = ModelConfig(
    name="Text",
)

string_format = text_format.MessageToString(config)
print(string_format)
```

I'm using `betterproto==1.2.5`

**Comment by Gobot1234** [comment] 2022-10-03 19:38
This seems like a duplicate of #251

**Closed by Gobot1234** 2022-10-03 19:38 UTC
